name: tests

on:
  push:
    branches:
      - dev
    tags-ignore:
      - '**'
  pull_request:

jobs:
  gofmt:
    name: Run gofmt
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Gofmt
        run: test -z "$(gofmt -l .)"

      - name: Show diff
        if: failure()
        run: gofmt -d -s .

  goimports:
    name: Run goimports
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run goimports
        run: test -z "$(set -o pipefail && $(go env GOPATH)/bin/goimports -l . | tee goimports.out)" || { cat goimports.out && exit 1; }

      - name: Open this to see how to fix goimports if it fails
        run: echo Run goimports -w .
        if: failure()

      - name: Build code
        # Use find to build all modules. '-execdir ... ;' doesn't set an exit code
        # based on command results. So, create a file if a build fails and check
        # if the file exists to set the right exit code.
        run: find . -name go.mod -execdir sh -c 'go build ./... || touch build_failed.txt' \; ; test ! -f build_failed.txt

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run GolangCI-Lint # https://github.com/golangci/golangci-lint
        run: docker run --rm -t -v $(pwd):/app -w /app golangci/golangci-lint:v1.48-alpine golangci-lint run -v

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Unit tests
        run: go test -v -race ./...

  build:
    name: Build for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux, darwin]
    needs: [gofmt, lint, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build application
        env:
          GOOS: ${{ matrix.os }}
        run: go build -ldflags="-s -w" -o /tmp/app .

      - uses: actions/upload-artifact@master
        with:
          name: app-${{ matrix.os }}-${{ env.version }}
          path: /tmp/app

  image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [gofmt, lint, test]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t app -f Dockerfile .
